name: Build Thesis PDF

on:
  push:
    branches: [ "master", "main", "dev" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          extra_system_packages: "ttf-arphic-ukai"

      - name: Rename PDF (Optional)
        run: mv main.pdf CCU_Thesis_Template.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis-PDF
          path: CCU_Thesis_Template.pdf
          retention-days: 5

  release:
    needs: build_latex
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Thesis-PDF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: CCU_Thesis_Template.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}